### ISSUE TITLE
Add date binning utility 

### ISSUE THREAD

**Issue by agritheory** [agritheory/forecast#8]
Having a date/period binning utility would be really handy for this project. Some high level requirements:

- Arbitrary start and end dates, able to consume or output partial periods
- Establish patterns around periodicity:
     - Week with arbitrary weekday start vs ISO week
     - Calendar month with remainders (EG Jan 15 to Mar 15, binning by calendar month would return a bin with Jan 15-31, Feb 1-28, Mar 1-15)
     - Various ISO month patterns (4 5 4, 4 4 5, 13 4-week months) - there isn't a specific convention here as far as I know, but several are used in practice.
     - It would be great to be able to convert a set of data from one set of period-based bins to another. This will be particularly handy when converting /distributing summary level calendar month data into ISO weeks, for example
     - It may be appropriate to have a separate abstraction(s)/ function for periodicity, which would allow for more reasonable testing of the binning parameters.
     - This feels like something that's in the itertools/more_itertools family, but with special rules. 
 
There are probably more requirements than just these above, I think it would make sense to start with some example data. We can design that offline to make sure it includes the sorts of test cases we want to hit on.

**Comment by HKuz** [comment]
Some initial thought after experimenting with this...

To keep things clear, here's how I'm using the following terms:
- Period: how we're breaking up the time span between start_date and end_date that the user provides (i.e Calendar Month would be Jan, Feb, ...)
- Stub period: an incomplete period (i.e. if the user wants Calendar months and their start date is 1/15, the first period would be a stub from 1/15-1/31)

I think big picture there will be two main logical branches in the code - one to calculate ISO date bins, one for calendar-based bins. (There may be other one-off things, like "Entire Period" we'll need to handle). Working off your code, I'm using the `get_dates` function as the main access point which can call other functions, depending on the branch, then it returns the bins of (from, to) periods. I have a working ISO function that handles the ISO options (tested so far on 2023 dates). Since ISO is all week-based, I just generate the start dates based off a 'step' that represents weeks to add. It can handle single values (1->weeks, 13->quarters) or sequences (4, 5, 4 -> months). I'm currently working on coding out the calendar branch, I think it can be something similar (a step as well as the part of the date to increment).

One point of discussion is how we want to handle a beginning stub period for ISO weeks (the specs above make clear that calendar dates definitely include it). ISO always starts on a Monday, and the user may not realize the date they feed in isn't that weekday. For example, 1/1/23 falls on a Sunday and is included in the last week of 2022, so the first 2023 ISO week is 1/2-1/8. Right now, my ISO code honors the user-entered start date so the first bin is a short period: for weeks, it would output [(1/1/23, 1/1/23), (1/2/23, 1/8/23),...]. We can discuss how this should work - the code can easily be modified to ignore the stub period or introduce a flag and let the user decide, depending on what we want to do.

Potential useful functionality we may want to consider: the user enters a start date, the periodicity, and the number of periods they want (vs an end date)

For testing, I've been working in a Jupyter notebook with a copied class. I have the start of a test suite there (2023 ISO dates cut weekly, 4+5+4 monthly, and 13 week quarterly). I can share that and continue to add to it for the other scenarios.
